version: "3.7"


services:

  zones:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-zpjq_j_wn+vpuy)te2nz8t)@!e(gxq2@*(-4+ng(4!j$$5vm#j#
      - ALLOWED_HOSTS=*
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
    depends_on:
      - postgis
    volumes:
      - ../:/app

  postgis:
    image: postgis/postgis:latest
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTRGES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgis/zone_data

volumes:
  postgres:
    driver: local