# Generated by Django 4.0.6 on 2022-07-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='poly',
            new_name='area',
        ),
    ]
