# Generated by Django 4.0.6 on 2022-07-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_rename_poly_zone_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='zones.zone'),
        ),
    ]
